"""engine_v1 baseline: tenant + llm_call, with RLS from creation

Revision ID: 0001_v1_baseline
Revises:
Create Date: 2026-08-06

Hand-written rather than autogenerated: schema creation and the RLS policies are not
things Alembic can infer, and `10 §4` requires the policies to exist from the table's
first day rather than being retrofitted.

RLS model: policies compare `tenant_id` against the `engine_v1.tenant_id` session GUC
that `v1.platform.db.session_scope` sets. `FORCE ROW LEVEL SECURITY` is deliberately
included so the table owner is subject to the policy too — without it, the app role
being the owner (the common single-role deployment) silently bypasses RLS and the
"backstop" protects nothing.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_v1_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "engine_v1"

# A NULL GUC (no tenant set) matches nothing — a query that forgot to set the tenant
# returns zero rows rather than every tenant's rows.
_TENANT_PREDICATE = "tenant_id = NULLIF(current_setting('engine_v1.tenant_id', true), '')::uuid"


def _enable_rls(table: str, predicate: str) -> None:
    op.execute(f'ALTER TABLE "{SCHEMA}"."{table}" ENABLE ROW LEVEL SECURITY')
    op.execute(f'ALTER TABLE "{SCHEMA}"."{table}" FORCE ROW LEVEL SECURITY')
    op.execute(
        f'CREATE POLICY {table}_tenant_isolation ON "{SCHEMA}"."{table}" '
        f"USING ({predicate}) WITH CHECK ({predicate})"
    )


def upgrade() -> None:
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA}"')

    op.create_table(
        "tenant",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name="pk_tenant"),
        sa.UniqueConstraint("slug", name="uq_tenant_slug"),
        schema=SCHEMA,
    )
    op.create_index("ix_tenant_created_at", "tenant", ["created_at"], unique=False, schema=SCHEMA)

    op.create_table(
        "llm_call",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("profile", sa.String(length=64), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("schema_name", sa.String(length=64), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tokens_out", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), nullable=False, server_default="0"
        ),
        sa.Column("cost_is_estimated", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_llm_call"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            [f"{SCHEMA}.tenant.id"],
            name="fk_llm_call_tenant_id_tenant",
            ondelete="CASCADE",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_llm_call_created_at", "llm_call", ["created_at"], unique=False, schema=SCHEMA
    )
    op.create_index(
        "ix_llm_call_correlation_id", "llm_call", ["correlation_id"], unique=False, schema=SCHEMA
    )
    op.create_index(
        "ix_llm_call_tenant_created", "llm_call", ["tenant_id", "created_at"], schema=SCHEMA
    )
    op.create_index(
        "ix_llm_call_tenant_task_created",
        "llm_call",
        ["tenant_id", "task", "created_at"],
        schema=SCHEMA,
    )

    _enable_rls(
        "tenant",
        "id = NULLIF(current_setting('engine_v1.tenant_id', true), '')::uuid",
    )
    _enable_rls("llm_call", _TENANT_PREDICATE)


def downgrade() -> None:
    op.execute(f'DROP POLICY IF EXISTS llm_call_tenant_isolation ON "{SCHEMA}"."llm_call"')
    op.execute(f'DROP POLICY IF EXISTS tenant_tenant_isolation ON "{SCHEMA}"."tenant"')
    op.drop_table("llm_call", schema=SCHEMA)
    op.drop_table("tenant", schema=SCHEMA)
