"""add_date_tba_and_community_submissions

Revision ID: 5568dd7d9489
Revises: f89f806ce2ff
Create Date: 2026-04-23 13:32:33.375953

"""

from alembic import op
import sqlalchemy as sa



revision = '5568dd7d9489'
down_revision = 'f89f806ce2ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_tba', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('manual_submissions', sa.Column('submission_type', sa.String(length=30), server_default='event', nullable=False))
    op.add_column('manual_submissions', sa.Column('community_name', sa.String(length=300), nullable=True))
    op.add_column('manual_submissions', sa.Column('community_url', sa.Text(), nullable=True))
    op.add_column('manual_submissions', sa.Column('community_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_submissions', 'community_description')
    op.drop_column('manual_submissions', 'community_url')
    op.drop_column('manual_submissions', 'community_name')
    op.drop_column('manual_submissions', 'submission_type')
    op.drop_column('events', 'date_tba')
    # ### end Alembic commands ###

