"""add_source_status_field

Revision ID: f89f806ce2ff
Revises: 20260421120000
Create Date: 2026-04-22 18:03:35.626839

"""

from alembic import op
import sqlalchemy as sa



revision = 'f89f806ce2ff'
down_revision = '20260421120000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_runs_source_id'), table_name='crawl_runs')
    op.drop_index(op.f('ix_raw_events_source_id'), table_name='raw_events')
    op.drop_index(op.f('uq_raw_events_source_external_id'), table_name='raw_events', postgresql_where='(external_id IS NOT NULL)')
    op.add_column('sources', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'status')
    op.create_index(op.f('uq_raw_events_source_external_id'), 'raw_events', ['source_id', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    op.create_index(op.f('ix_raw_events_source_id'), 'raw_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_source_id'), 'crawl_runs', ['source_id'], unique=False)
    # ### end Alembic commands ###

